### ISSUE TITLE
missing examples

### ISSUE THREAD

**Issue by gnuday** [singlecomm/luaphonenumber#2]
Hi. Many thanks for the lua port. Any chance of an example or two? I've only used the python port of this library so far. An example of number validation or converting to e164 would be greatly appreciated. Thanks again.

**Comment by cdosoftei** [comment]
I've just updated the project's [README](https://github.com/singlecomm/luaphonenumber/blob/master/README.md) file -- I think you'll find the necessary information there.

**Comment by gnuday** [comment]
Hi,

Thank you so much! Have a great weekend.

Regards,
John
